name: QA Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'api-1/**'
      - 'api-2/**'

jobs:
  api-1:
    if: contains(github.event.head_commit.message, 'api-1')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js (or any environment your API uses)
      run: echo "Running for api-1"


  api-2:
    if: contains(github.event.head_commit.message, 'api-2')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js (or any environment your API uses)
      run: echo "Running for api-2"
